#!/bin/bash

echo "==================================================================="
echo "CUDA 12 Installation Commands for Ubuntu 24.04"
echo "==================================================================="
echo ""
echo "Please run these commands in a terminal with sudo access:"
echo ""
echo "# 1. Add NVIDIA package repositories"
echo "wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb"
echo "sudo dpkg -i cuda-keyring_1.1-1_all.deb"
echo ""
echo "# 2. Update apt and install CUDA toolkit 12.4"
echo "sudo apt update"
echo "sudo apt install -y cuda-toolkit-12-4"
echo ""
echo "# 3. Add CUDA to PATH (add to ~/.bashrc)"
echo "export PATH=/usr/local/cuda-12.4/bin:\$PATH"
echo "export LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64:\$LD_LIBRARY_PATH"
echo ""
echo "# 4. Verify installation"
echo "nvcc --version"
echo ""
echo "==================================================================="
echo "Alternative: Install just the runtime libraries (smaller)"
echo "==================================================================="
echo ""
echo "sudo apt install -y cuda-cudart-12-4 libcublas-12-4 libcusparse-12-4"
echo ""
echo "==================================================================="