#!/bin/bash

echo "==================================================================="
echo "CUDA 12 Installation - Fixed Commands"
echo "==================================================================="
echo ""
echo "# 1. Remove the CD-ROM repository that's causing issues:"
echo "sudo sed -i '/cdrom/d' /etc/apt/sources.list"
echo ""
echo "# 2. Download and add NVIDIA CUDA repository:"
echo "wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb"
echo "sudo dpkg -i cuda-keyring_1.1-1_all.deb"
echo ""
echo "# 3. Update package list:"
echo "sudo apt update"
echo ""
echo "# 4. Install CUDA 12.4 runtime libraries only (faster, smaller):"
echo "sudo apt install -y cuda-cudart-12-4 cuda-compat-12-4"
echo ""
echo "# OR install full CUDA toolkit (larger, includes compiler):"
echo "sudo apt install -y cuda-12-4"
echo ""
echo "# 5. Set up environment variables (add to ~/.bashrc):"
echo "echo 'export PATH=/usr/local/cuda-12/bin:\$PATH' >> ~/.bashrc"
echo "echo 'export LD_LIBRARY_PATH=/usr/local/cuda-12/lib64:\$LD_LIBRARY_PATH' >> ~/.bashrc"
echo "source ~/.bashrc"
echo ""
echo "# 6. Create symbolic link for vLLM:"
echo "sudo ln -sf /usr/local/cuda-12/lib64/libcudart.so.12 /usr/lib/x86_64-linux-gnu/"
echo ""
echo "==================================================================="